spring.datasource.url=jdbc:mysql://${PEDIDOS_MYSQL_HOST}:${PEDIDOS_MYSQL_PORT}/${PEDIDOS_MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${PEDIDOS_MYSQL_USERNAME}
spring.datasource.password=${PEDIDOS_MYSQL_PASSWORD}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.h2.console.enabled=false
app.security.docs-public=false

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
